/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author theda
 */
public class mathGUI extends javax.swing.JFrame {

    /**
     * Creates new form mathGUI
     */
    public mathGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        inputLabel = new javax.swing.JLabel();
        num1Input = new javax.swing.JTextField();
        num2Input = new javax.swing.JTextField();
        num3Input = new javax.swing.JTextField();
        methodDropDown = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        methodDescOutput = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        mathMethodOutput = new javax.swing.JTextPane();
        displayButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titleLabel.setText("Math Method Examples:");

        inputLabel.setText("Please Enter Multiple Numbers:");

        num1Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1InputActionPerformed(evt);
            }
        });

        num2Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2InputActionPerformed(evt);
            }
        });

        num3Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3InputActionPerformed(evt);
            }
        });

        methodDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "default", "Round", "Random", "Min", "Max", "Square Root" }));
        methodDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                methodDropDownActionPerformed(evt);
            }
        });

        jLabel1.setText("Please Pick A Method:");

        methodDescOutput.setEditable(false);
        jScrollPane1.setViewportView(methodDescOutput);

        mathMethodOutput.setEditable(false);
        jScrollPane2.setViewportView(mathMethodOutput);

        displayButton.setText("Show Example");
        displayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Decimal");

        jLabel3.setText("Whole Value");

        jLabel4.setText("Whole Value");

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(titleLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(inputLabel)
                        .addComponent(jLabel1))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(methodDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(displayButton))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel2))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(num1Input, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(num2Input, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(num3Input, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputLabel)
                    .addComponent(num1Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num2Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num3Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(methodDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(displayButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num1InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num1InputActionPerformed

    private void num2InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num2InputActionPerformed

    private void num3InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num3InputActionPerformed

    private void methodDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_methodDropDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_methodDropDownActionPerformed

    private void displayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayButtonActionPerformed
        // TODO add your handling code here:
        int num1, num2, methodSelect; //Declaring variables
        num1 = Integer.parseInt(num1Input.getText()); ////Convert the users selected choice to a int
        num2 = Integer.parseInt(num2Input.getText());
        methodSelect = methodDropDown.getSelectedIndex(); //Gets the index of the option the user selected within the combo box
        float num3 = Float.parseFloat(num3Input.getText()); //Fetchs the decimal input
        
        //System.out.println(methodSelect); //Debug to see value of index in case of a unexpected output

        switch (methodSelect) { //Comapre the selected index to values 0-5
            case 0:
                methodDescOutput.setText("You have not selected a Math method."); //User did not select a math method
                mathMethodOutput.setText("You have not selected a Math method.");
                break;
            case 1: //Round
                methodDescOutput.setText("The Math.round() method takes a value and rounds it to the nearest whole number. Input a decimal value into the third input space"); 
                mathMethodOutput.setText("Rounded Number: " + Math.round(num3)); //Rounds the num3 input
                break;
            case 2: //Random
                double randomNum = Math.random();
                methodDescOutput.setText("The Math.random() method generates a random value. No input needed.");
                mathMethodOutput.setText("Random Number: " + randomNum); //Generates random value
                break;
            case 3: //Min         
                methodDescOutput.setText("The Math.min() method takes two values and returns the smallest one. Please input values into the first two input spaces");
                mathMethodOutput.setText("Input Numbers: " + num1 + " " + num2 + "\n" + "Minimum Value: " + Math.min(num1, num2)); //Compares two values and returns the lowest
                break;
            case 4://Max             
                methodDescOutput.setText("The Math.max() method takes two values and returns the largest one.");
                mathMethodOutput.setText("Input Numbers: " + num1 + " " + num2 + "\n" + "Maximum Value: " + Math.max(num1, num2)); //Compares two values and returns the highest
                break;
            case 5://Sqaure Root
                methodDescOutput.setText("The Math.sqrt() method takes a value and returns the square root of it. Please input a perfect square in the first input space: 1, 4, 9, 16, 25, 36 if you would like a whole value returned");
                mathMethodOutput.setText("Input Number: " + num1 + "\n" + "Square Root Value: " + Math.sqrt(num1)); //Returns the square rot of the value
                break;

            default:
                break;
        }
    }//GEN-LAST:event_displayButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        methodDescOutput.setText(" "); //Clears the output fields
        mathMethodOutput.setText(" ");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mathGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mathGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mathGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mathGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mathGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton displayButton;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane mathMethodOutput;
    private javax.swing.JTextPane methodDescOutput;
    private javax.swing.JComboBox<String> methodDropDown;
    private javax.swing.JTextField num1Input;
    private javax.swing.JTextField num2Input;
    private javax.swing.JTextField num3Input;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
